name: sophgo-edk2-build

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build-edk2:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        M_PLAT_NAME: [SG2042-EVB, MilkV-Pioneer, SRA1-20]

    env:
      mainline_elf_toolchain: https://github.com/riscv-collab/riscv-gnu-toolchain/releases/download/2023.12.14
      mainline_elf_toolchain_file_name: riscv64-elf-ubuntu-22.04-gcc-nightly-2023.12.14-nightly.tar.gz
      wget_alias: 'wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 0'
      CHIP: mango
      PLAT: ${{ matrix.M_PLAT_NAME }}
    
    steps:
      - name: Install toolchains
        run: |
              ${wget_alias} ${mainline_elf_toolchain}/${mainline_elf_toolchain_file_name}
              tar -xvf ${mainline_elf_toolchain_file_name} -C /opt

      - name: Install software
        run: |
              sudo apt update && \
              sudo apt install -y autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk \
                                  build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev \
                                  ninja-build uuid-dev gcc-riscv64-unknown-elf acpica-tools

      - name: Checkout sophgo-edk2
        uses: actions/checkout@v4
        with:
          repository: sophgo/sophgo-edk2
          path: sophgo-edk2
          ref: devel-sg2042
          submodules: recursive
      
      - name: prepare
        run: mkdir -p artifact

      - name: Compile edk2
        working-directory: sophgo-edk2
        run: |
              export PATH="/opt/riscv/bin:$PATH"
              export WORKSPACE=`pwd`
              export PACKAGES_PATH=$WORKSPACE/edk2:$WORKSPACE/edk2-platforms:$WORKSPACE/edk2-non-osi
              export GCC5_RISCV64_PREFIX=riscv64-unknown-elf-
              source edk2/edksetup.sh
              make -C edk2/BaseTools
              build -a RISCV64 -t GCC5 -b RELEASE -D ACPI_ENABLE -p Platform/Sophgo/SG2042Pkg/${PLAT}/${PLAT}.dsc
              cp -v $WORKSPACE/Build/${PLAT}/RELEASE_GCC5/FV/${PLAT^^}.fd $GITHUB_WORKSPACE/artifact/${PLAT}.fd

      - name: 'Upload Build Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: sophgo-edk2-${{ matrix.M_PLAT_NAME }}
          path: artifact/
          retention-days: 30
